old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            keepalive: false
            heartbeat: 0
            use_socket: true
    producers:
        create_gift_select:
            connection:       default
            exchange_options: { name: 'create_gift_select.v1', type: direct }

    consumers:
        create_gift_select:
            connection:       default
            exchange_options: { name: 'create_gift_select.v1', type: direct }
            queue_options:    { name: 'create_gift_select.v1' }
            callback:         app.consumer.gift_select